
services:
  provider:
    build:
      context: ./provider
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - api_internal
      - executors

  connector:
    build:
      context: ./connector
      dockerfile: Dockerfile
    restart: always
    environment:
      - SSH_USER=${SSH_USER}
      - SSH_HOST=${SSH_HOST}
      - SSH_PORT=${SSH_PORT}
      - OUT_API_PORT=${OUT_API_PORT}
      - IN_API_PORT=${IN_API_PORT}
      - API_HOST=provider
    volumes:
      - ./connector/certificate/known_hosts:/root/.ssh/known_hosts
    networks:
      - api_internal

networks:
  executors:
    driver: bridge
  api_internal:
    driver: bridge
