
services:
  openssh:
    image: lscr.io/linuxserver/openssh-server:latest
    hostname: openssh
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - SUDO_ACCESS=false
      - PASSWORD_ACCESS=false
      - USER_NAME=userus
      - LOG_STDOUT=true
      - DOCKER_MODS=linuxserver/mods:openssh-server-ssh-tunnel
    volumes:
      - ./sshconfig/authorized_keys:/config/.ssh/authorized_keys
      - ./sshconfig/host_keys:/config/ssh_host_keys/
    expose:
      - ${OUT_API_PORT}
    ports:
      - ${SSH_PORT}:2222
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: unless-stopped
